language: python
python:
- 3.6

install:
- pip install --index-url https://${PYPI_USERNAME}:${PYPI_PASSWORD}@${PYPI_HOST} "secrets_shield<1.0.0"

script:
- secrets-shield --token=${GG_SCANNING_API_TOKEN} scan --ci
