version: 2.1

orbs:
  compare-url: iynere/compare-url@0.2

workflows:
  version: 2
  secrets-shield:
    jobs:
      - compare-url/reconstruct
      - secrets-shield:
          requires:
            - compare-url/reconstruct

jobs:
  secrets-shield:
    docker:
      - image: python:3.6-slim
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run:
          name: Secrets Shield
          command: |
            CIRCLE_COMPARE_URL=$(cat workspace/CIRCLE_COMPARE_URL.txt)
            export CIRCLE_COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')

            pip install pip==19.1.1
            apt-get update && apt-get -y install git

            pip install --index-url https://${PYPI_USERNAME}:${PYPI_PASSWORD}@${PYPI_HOST} "secrets_shield<1.0.0"
            secrets-shield --token=${GG_SCANNING_API_TOKEN} scan --ci -v
